// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFZXMQylwxQ-hunIkRzN2E19EjCiI2Nqs',
    appId: '1:943310795135:web:831129d9dcaf7849d92a4a',
    messagingSenderId: '943310795135',
    projectId: 'fitgo-35249',
    authDomain: 'fitgo-35249.firebaseapp.com',
    storageBucket: 'fitgo-35249.firebasestorage.app',
    measurementId: 'G-HZ2SC5J89P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrKPzQYALjDWq5RE2vbontgGuOXasrT1w',
    appId: '1:943310795135:android:1fb6e4791aff7b53d92a4a',
    messagingSenderId: '943310795135',
    projectId: 'fitgo-35249',
    storageBucket: 'fitgo-35249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGjiLyiA2bYwRTk6aCo_qmIDfB9BM4sgw',
    appId: '1:943310795135:ios:ecb7c0b1c5d2a65dd92a4a',
    messagingSenderId: '943310795135',
    projectId: 'fitgo-35249',
    storageBucket: 'fitgo-35249.firebasestorage.app',
    iosBundleId: 'com.example.fitgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGjiLyiA2bYwRTk6aCo_qmIDfB9BM4sgw',
    appId: '1:943310795135:ios:ecb7c0b1c5d2a65dd92a4a',
    messagingSenderId: '943310795135',
    projectId: 'fitgo-35249',
    storageBucket: 'fitgo-35249.firebasestorage.app',
    iosBundleId: 'com.example.fitgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFZXMQylwxQ-hunIkRzN2E19EjCiI2Nqs',
    appId: '1:943310795135:web:2347b5f6450c11e2d92a4a',
    messagingSenderId: '943310795135',
    projectId: 'fitgo-35249',
    authDomain: 'fitgo-35249.firebaseapp.com',
    storageBucket: 'fitgo-35249.firebasestorage.app',
    measurementId: 'G-S9XT293NG2',
  );
}
